[package]
name = "fas-rs"
version = "2.2.0"
edition = "2021"
description = "Frame aware scheduling for android"
authors = ["shadow3"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/shadow3aaa/fas-rs"

[workspace]
exclude = ["zygisk/rust"]

[dependencies]
likely_stable = "0.1.2"
parking_lot = "0.12.1"
log = "0.4.20"
anyhow = "1.0.79"
thiserror = "1.0.56"
inotify = { version = "0.10.2", default-features = false }
libc = "0.2.152"
async-trait = "0.1.77"
binder = { package = "binder_ndk", version = "0.2.0" }
lazy_static = "1.4.0"
once_cell = "1.19.0"
flexi_logger = "0.27.4"
toml = "0.8.8"
serde = { version = "1.0.196", features = ["derive"] }
rlua = "0.19.8"
smallvec = "1.13.1"
cpu_cycles_reader = "1.0.0"
sys-mount = { version = "3.0.1", default-features = false }
quick-xml = { version = "0.31.0", features = ["serialize"] }

[build-dependencies]
anyhow = "1.0.79"
toml = "0.8.8"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"

[profile.dev]
overflow-checks = false
lto = "thin"
opt-level = 3
strip = true

[profile.release]
overflow-checks = false
codegen-units = 1
lto = "fat"
opt-level = 3
strip = true
