[package]
name = "fas-rs"
version = "0.1.2"
edition = "2021"
description = "Frame-aware scheduling binary"
authors = ["shadow3"]
license = "WTFPL"
readme = "README.md"
repository = "https://github.com/shadow3aaa/fas-rs"

[workspace]
members = ['fas-rs-fw']

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpu_cycles_reader = "0.1.31"
lazy_static = "1.4.0"
likely_stable = "0.1.2"
parking_lot = "0.12.1"
toml = "0.7.5"
fas-rs-fw = { path = "./fas-rs-fw" }
inotify = { version = "0.10.1", default_features = false }
yata = { version = "0.6.1", default_features = false }
atomic = "0.5.3"

[build-dependencies]
toml = "0.7.5"
serde = "1.0.167"
serde_derive = "1.0.167"

[profile.dev]
panic = 'abort'

[profile.release]
codegen-units = 1
lto = 'fat'
opt-level = 3
strip = true
panic = 'abort'
