[package]
name = "fas-rs"
version = "0.1.0"
edition = "2021"

[workspace]
members = ['fas-rs-fw']

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fas-rs-fw = { path = "./fas-rs-fw" }
inotify = {version = "0.10.1", default_features = false}
spin_sleep = "1.1.1"

[profile.release]
lto = 'fat'
codegen-units = 1
opt-level = 3
strip = true
panic = 'abort'
