[package]
name = "fas-rs"
version = "2.7.0"
edition = "2021"
description = "Frame aware scheduling for android"
authors = ["shadow3"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/shadow3aaa/fas-rs"

[features]
default = ["use_ebpf"]
use_ebpf = []
use_binder = ["binder"]

[workspace]
exclude = ["zygisk/rust"]

[dependencies]
likely_stable = "0.1.2"
parking_lot = "0.12.1"
log = "0.4.21"
anyhow = "1.0.82"
thiserror = "1.0.59"
inotify = { version = "0.10.2", default-features = false }
libc = "0.2.152"
async-trait = "0.1.80"
binder = { package = "binder_ndk", git = "https://github.com/shadow3aaa/binder_rs", optional = true }
lazy_static = "1.4.0"
flexi_logger = "0.28.0"
toml = "0.8.12"
serde = { version = "1.0.198", features = ["derive"] }
cpu_cycles_reader = "1.0.1"
sys-mount = { version = "3.0.1", default-features = false }
quick-xml = { version = "0.31.0", features = ["serialize"] }
mlua = { version = "0.9.7", features = ["luajit", "vendored"] }
frame-analyzer = "0.2.0"

[build-dependencies]
anyhow = "1.0.82"
toml = "0.8.12"
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"

[profile.dev]
overflow-checks = false
opt-level = 3
strip = true

[profile.release]
overflow-checks = false
codegen-units = 1
lto = "fat"
opt-level = 3
strip = true
