# Copyright 2023 shadow3aaa@gitbub.com
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[package]
name = "fas-rs"
version = "2.7.0"
edition = "2021"
description = "Frame aware scheduling for android."
authors = ["shadow3"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/shadow3aaa/fas-rs"

[features]
default = ["use_ebpf"]
use_ebpf = ["frame-analyzer"]
use_binder = ["binder"]

[workspace]
exclude = ["zygisk/rust"]

[dependencies]
likely_stable = "0.1.2"
parking_lot = "0.12.1"
log = "0.4.21"
anyhow = "1.0.82"
thiserror = "1.0.59"
inotify = { version = "0.10.2", default-features = false }
libc = "0.2.153"
async-trait = "0.1.80"
binder = { package = "binder_ndk", git = "https://github.com/shadow3aaa/binder_rs", optional = true }
lazy_static = "1.4.0"
flexi_logger = "0.28.0"
toml = "0.8.12"
serde = { version = "1.0.198", features = ["derive"] }
cpu_cycles_reader = "1.0.1"
sys-mount = { version = "3.0.1", default-features = false }
quick-xml = { version = "0.31.0", features = ["serialize"] }
mlua = { version = "0.9.7", features = ["luajit", "vendored"] }
frame-analyzer = { version = "0.2.6", optional = true }

[build-dependencies]
anyhow = "1.0.82"
toml = "0.8.12"
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"

[profile.dev]
overflow-checks = false
opt-level = 3
strip = true

[profile.release]
overflow-checks = false
codegen-units = 1
lto = "fat"
opt-level = 3
strip = true
