[config]
ignore_little = false
keep_std = true
min_step = 20

[game_list]
"com.hypergryph.arknights" = 60
"com.miHoYo.Yuanshen" = 60
"com.miHoYo.enterprise.NGHSoD" = 60
"com.miHoYo.hkrpg" = 60
"com.mojang.minecraftpe" = 120
"com.netease.x19" = 120
"com.pixeltoys.freeblade" = 60
"com.prpr.musedash.TapTap" = 60
"com.shangyoo.neon" = 60
"com.tencent.tmgp.pubgmhd" = 60
"com.tencent.tmgp.sgame" = 120
