[config]
ignore_little = false
keep_std = true

[game_list]
"com.hypergryph.arknights" = "auto"
"com.miHoYo.Yuanshen" = "auto"
"com.miHoYo.enterprise.NGHSoD" = "auto"
"com.miHoYo.hkrpg" = "auto"
"com.mojang.minecraftpe" = "auto"
"com.netease.party" = "auto"
"com.netease.x19" = "auto"
"com.pixeltoys.freeblade" = "auto"
"com.prpr.musedash.TapTap" = "auto"
"com.shangyoo.neon" = "auto"
"com.tencent.tmgp.pubgmhd" = "auto"
"com.tencent.tmgp.sgame" = "auto"

[powersave]
jank_keep_count = 15
normal_keep_count = 5
tolerant_big_jank = 5000
tolerant_jank = 2750
tolerant_unit = 4

[balance]
jank_keep_count = 25
normal_keep_count = 5
tolerant_big_jank = 3000
tolerant_jank = 1500
tolerant_unit = 3

[performance]
jank_keep_count = 30
normal_keep_count = 5
tolerant_big_jank = 2000
tolerant_jank = 1250
tolerant_unit = 2

[fast]
jank_keep_count = 30
normal_keep_count = 6
tolerant_big_jank = 1450
tolerant_jank = 1000
tolerant_unit = 1
