[config]
ignore_little = false
keep_std = true

[powersave]
normal_keep_count = 8
jank_keep_count = 30
tolerant_jank = 900
tolerant_big_jank = 1850
tolerant_unit = 5

[balance]
normal_keep_count = 8
jank_keep_count = 30
tolerant_jank = 800
tolerant_big_jank = 1750
tolerant_unit = 5

[performance]
normal_keep_count = 8
jank_keep_count = 30
tolerant_jank = 650
tolerant_big_jank = 1550
tolerant_unit = 5

[fast]
normal_keep_count = 8
jank_keep_count = 30
tolerant_jank = 550
tolerant_big_jank = 1450
tolerant_unit = 5

[game_list]
"com.hypergryph.arknights" = "auto"
"com.miHoYo.Yuanshen" = "auto"
"com.miHoYo.enterprise.NGHSoD" = "auto"
"com.miHoYo.hkrpg" = "auto"
"com.mojang.minecraftpe" = "auto"
"com.netease.party" = "auto"
"com.netease.x19" = "auto"
"com.pixeltoys.freeblade" = "auto"
"com.prpr.musedash.TapTap" = "auto"
"com.shangyoo.neon" = "auto"
"com.tencent.tmgp.pubgmhd" = "auto"
"com.tencent.tmgp.sgame" = "auto"
