[config]
ignore_little = false
keep_std = true

[game_list]
"com.hypergryph.arknights" = "auto"
"com.miHoYo.Yuanshen" = "auto"
"com.miHoYo.enterprise.NGHSoD" = "auto"
"com.miHoYo.hkrpg" = "auto"
"com.mojang.minecraftpe" = "auto"
"com.netease.party" = "auto"
"com.netease.wotb" = "auto"
"com.netease.x19" = "auto"
"com.pixeltoys.freeblade" = "auto"
"com.prpr.musedash.TapTap" = "auto"
"com.shangyoo.neon" = "auto"
"com.tencent.tmgp.pubgmhd" = "auto"
"com.tencent.tmgp.sgame" = "auto"

[powersave]
jank_rec_count = 4
normal_rec_count = 6
tolerant_frame_limit = 4.8
tolerant_frame_jank = 5.0

[balance]
jank_rec_count = 10
normal_rec_count = 4
tolerant_frame_limit = 2.8
tolerant_frame_jank = 3.0

[performance]
jank_rec_count = 16
normal_rec_count = 8
tolerant_frame_limit = 1.3
tolerant_frame_jank = 1.5

[fast]
jank_rec_count = 16
normal_rec_count = 8
tolerant_frame_limit = 0.8
tolerant_frame_jank = 1.0
