[config]
EMA_TYPE = "SMA"
EMA_WIN = 4
default_target_diff = 450
default_target_diff_fas = 600
diff_move = 50
ignore_little = true
jank_diff = 145
keep_std = true
slide_boost = 2
slide_timer = 175
touch_boost = 1

[game_list]
"com.miHoYo.Yuanshen" = 60
"com.miHoYo.enterprise.NGHSoD" = 60
"com.miHoYo.hkrpg" = 60
"com.mojang.minecraftpe" = 120
"com.netease.x19" = 120
"com.pixeltoys.freeblade" = 60
"com.prpr.musedash.TapTap" = 60
"com.tencent.tmgp.pubgmhd" = 60
"com.tencent.tmgp.sgame" = 120
