[config]
EMA_TYPE = "SMA"
EMA_WIN = 4
default_target_diff = 450
default_target_diff_fas = 600
diff_move = 75
dumpsys_prefix = 115
ignore_little = true
jank_diff = 145
keep_std = true
slide_boost = 3
slide_timer = 200
touch_boost = 2

[game_list]
"com.miHoYo.Yuanshen" = [60, 10]
"com.miHoYo.enterprise.NGHSoD" = [60, 10]
"com.miHoYo.hkrpg" = [60, 10]
"com.mojang.minecraftpe" = [120, 10]
"com.netease.x19" = [120, 10]
"com.pixeltoys.freeblade" = [60, 10]
"com.prpr.musedash.TapTap" = [60, 10]
"com.tencent.tmgp.pubgmhd" = [60, 10]
"com.tencent.tmgp.sgame" = [120, 10]
