[config]
keep_std = true
EMA_TYPE = "SMA"
EMA_WIN = 4
always_on_gov = false
default_target_diff = 450
default_target_diff_fas = 600
ignore_little = true
jank_diff = 150
dumpsys_prefix = 100
diff_move = 75
slide_boost = 2
touch_boost = 1
slide_timer = 200

[game_list]
com.miHoYo.Yuanshen = [60, 10]
com.miHoYo.enterprise.NGHSoD = [60, 10]
com.miHoYo.hkrpg = [60, 10]
com.mojang.minecraftpe = [120, 10]
com.netease.x19 = [120, 10]
com.pixeltoys.freeblade = [60, 10]
com.prpr.musedash.TapTap = [60, 10]
com.tencent.tmgp.pubgmhd = [60, 10]
com.tencent.tmgp.sgame = [120, 10]
