[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
android_logger = "0.13.3"
cpp_demangle = "0.4.3"
dobby-api = "0.1.6"
goblin = "0.7.1"
libc = "0.2.149"
log = "0.4.20"
anyhow = "1.0.75"
async-trait = "0.1.74"
binder = { package = "binder_ndk", version = "0.2.0" }
lazy_static = "1.4.0"
once_cell = "1.18.0"
thiserror = "1.0.50"

[profile.dev]
overflow-checks = false

[profile.release]
overflow-checks = false
codegen-units = 1
lto = 'fat'
opt-level = 3
strip = true
panic = 'abort'
