[package]
name = 'fas-rs-fw'
version = '0.1.8'
edition = '2021'
description = 'Frame-aware scheduling framework'
license = 'Apache-2.0'
repository = 'https://github.com/shadow3aaa/fas-rs'
keywords = [
    'framework',
    'scheduling',
    'fas',
]
categories = [
    'game',
    'api',
]

[dependencies]
atomic = '0.5.3'
lazy_static = '1.4.0'
likely_stable = '0.1.2'
log = '0.4.19'
parking_lot = '0.12.1'
serde = '1.0.178'
serde_derive = '1.0.178'
toml = '0.7.6'
unix-named-pipe = "0.2.0"

[dependencies.inotify]
version = '0.10.2'
default_features = false
