[package]
name = "fas-rs-fw"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
lto = 'fat'
codegen-units = 1
opt-level = 3
strip = true
panic = 'abort'