[package]
name = "fas-rs-fw"
version = "0.3.0"
edition = "2021"
description = "Frame-aware scheduling framework"
license = "Apache-2.0"
repository = "https://github.com/shadow3aaa/fas-rs"

[dependencies]
likely_stable = "0.1.2"
log = "0.4.19"
parking_lot = "0.12.1"
serde = "1.0.178"
serde_derive = "1.0.178"
thiserror = "1.0.47"
toml = "0.7.6"
binder-rust = { git = "https://github.com/shadow3aaa/binder-rust" }
unix-named-pipe = "0.2.0"
num-traits = "0.2.16"
num-derive = "0.4.0"

[dependencies.inotify]
version = "0.10.2"
default_features = false
