[package]
name = "fas-rs-fw"
version = "0.1.2"
edition = "2021"
description = "Frame-aware scheduling framework"
license = "WTFPL"
repository = "https://github.com/shadow3aaa/fas-rs"
keywords = ["framework", "scheduling", "fas"]
categories = ["game", "api"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atomic = "0.5.3"
likely_stable = "0.1.2"
