name: ci-build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup deps
      run: |
        rustup target add aarch64-linux-android
        cargo install cargo-ndk
        sudo apt install zip
    - name: build
      run: make -f makefile-ndk
