name: ci-build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: nightly
        override: true
        target: aarch64-linux-android
    - name: Setup deps
      run: |
        cargo install cargo-ndk
        apt install zip
    - name: build
      run: make -f makefile-ndk
