name: ci-build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: nttld/setup-ndk@v1.4.1
      with:
        ndk-version: r26b
    - run: |
        rustup default nightly
        rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android i686-linux-android
    - run: cargo install cargo-ndk
    - run: |
        sudo apt update
        sudo apt upgrade
        sudo apt install gcc-multilib git-lfs
    - run: git lfs pull
    - name: check codes
      run: |
        cargo ndk -t arm64-v8a --platform=29 check --verbose --target aarch64-linux-android
        cd zygisk/rust && cargo ndk -t arm64-v8a --platform=29 check --verbose --target aarch64-linux-android
    - name: build
      run: sh build.sh release
