name: ci-build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: nttld/setup-ndk@v1.4.1
      with:
        ndk-version: r26b
        add-to-path: false
        local-cache: true
    - run: |
        rustup default nightly
        rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android i686-linux-android
    - run: cargo install cargo-ndk
    - run: |
        sudo apt update
        sudo apt install gcc-multilib git-lfs
    - run: git lfs pull
    - name: build
      run: |
        chmod +x ./build.sh
        ./build.sh --release
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
